### ISSUE TITLE
Set up VM for local dev

### ISSUE THREAD

**Issue by sarahjean** [Drupal4Gov/Drupal-GovCon-2016#2]
This will be optional, but there will be a configured drupal-vm setup in the codebase to make it easy to get going

**Comment by Nneka** [comment]
Is this vagrant?  If so, I have one that I use for development that can easily be tweaked for Drupal-GovCon use.

**Comment by sarahjean** [comment]
@Nneka We've got this set up, it is vagrant, right now some lightly customized config on http://www.drupalvm.com/

**Comment by alisonjo315** [comment]
Sorry for slacking and not paying attention -- is this so that we can efficiently get set up with consistent local dev environments?  If so, are there instructions for doing so -- if so, where?  Thanks :)
