### ISSUE TITLE
Quick prelaunch theme updates

### ISSUE THREAD

**Issue by sarahjean** [Drupal4Gov/Drupal-GovCon-2016#63]
Fixes for homepage and major sections before soft launch

**Comment by charlieartist** [comment]
Will need to add the text and styling elements from the splash page homepage. In addition, we also will need the hero image and the map. The structures are there in Features, so it's just adding new content to the site. Generally, typography looks OK.

Also, from other things:
- Sponsors--ought to be turned off, until updated.
- Twitter feed--looks a bit outdated, no recent updates, good to hide.
- Community--this looks like a search page, privacy issue.

**Comment by sarahjean** [comment]
Well, the twitter feed is up to date with the twitter account, I assume thats going to get some more updates as soon as we have the site up so I am good with leaving it.

Sponsors is going to be updated so we will leave that.

Community is a standard page, and was up last year so I don't think thats an issue either.

**Comment by charlieartist** [comment]
Homepage layout fixed.
