### ISSUE TITLE
Investigate and discuss per-day tickets for 2016

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2016#69]
_From @timwood on July 13, 2015 14:44_

_Copied from original issue: Drupal4Gov/Drupal-GovCon-2015#128_

**Comment by bendygirl** [comment]
I think we can close this as the intent was to implement this to ensure lunches are run more smoothly. The new registration asks users which days they are planning to attend, this should help us with lunch numbers.
