### ISSUE TITLE
Link "sponsors" and "volunteers" from footer

### ISSUE THREAD

**Issue by timwood** [Drupal4Gov/Drupal-GovCon-2016#70]
We have a Drupal GovCon team page which we can link the word "volunteers" from this footer sentence as well as link "sponsors" to the sponsors page.

https://www.drupalgovcon.org/drupal-govcon-2016/meet-drupal-govcon-team

https://www.drupalgovcon.org/drupal-govcon-2016/sponsors (styling isn't quite right yet). 

Full sentence in footer: Drupal GovCon is made possible by our wonderful sponsors and volunteers.
<img width="508" alt="screen shot 2016-05-08 at 12 10 37 am" src="https://cloud.githubusercontent.com/assets/91050/15096025/903b3d96-14b4-11e6-9e92-1e996731646b.png">

This sentence is managed in a custom code pane in the Panels Everywhere site_template page and is currently "in code". https://www.drupalgovcon.org/admin/structure/pages/edit/site_template

**Comment by charlieartist** [comment]
This has been fixed and tested.
