### ISSUE TITLE
Link on homepage to Submit Session returns an error

### ISSUE THREAD

**Issue by jamiebeemac** [Drupal4Gov/Drupal-GovCon-2016#79]
The Submit Session button on home has an incorrect link

This is for anon users only

The link is https://www.drupalgovcon.org/node/add/session/ and should be https://www.drupalgovcon.org/user?destination=node/add/session

**Comment by charlieartist** [comment]
This has been fixed, both in the homepage hero and in the News announcement currently on the homepage.
