### ISSUE TITLE
Need to hide session presenter names/image during session selection

### ISSUE THREAD

**Issue by jamiebeemac** [Drupal4Gov/Drupal-GovCon-2016#86]
During session selection we need to hid the session presenter name(s) and picture(s) from the display.

This is to account for blind session selection.

**Comment by charlieartist** [comment]
This could be accomplished via CSS, without making structural changes. Another way of doing it would be hiding it from export to XLS (there's a module for that). Any thoughts?

**Comment by jamiebeemac** [comment]
Honestly I thought we would just do it by changing the "Speaker" field to hidden in the content type
I just want to make sure it  is captured in Features

**Comment by jamiebeemac** [comment]
Oh and the xls export is not enough, we need to review the sessions on the site (Much easier to read)

**Comment by timwood** [comment]
Could we just temporarily clone the sessions view and locate it at some alternate URL and in that cloned view, remove the speaker output in the view? This isn't something that permanent, only for selection, right?

**Comment by sarahjean** [comment]
We will revisit this for next year but session selection is now completed so closing this.
